"""external_call_attempts run_id nullable

Revision ID: 6d9c4e4f2171
Revises: 7fe4c195842d
Create Date: 2026-08-20 12:20:07.449858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d9c4e4f2171'
down_revision: Union[str, Sequence[str], None] = '7fe4c195842d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('external_call_attempts', 'run_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('external_call_attempts', 'run_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
