"""add contacts.erased_at for GDPR erasure

Revision ID: 6fca51250783
Revises: 6d9c4e4f2171
Create Date: 2026-08-20 13:50:24.757642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fca51250783'
down_revision: Union[str, Sequence[str], None] = '6d9c4e4f2171'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('erased_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'erased_at')
    # ### end Alembic commands ###
