"""initial schema

Revision ID: 7fe4c195842d
Revises: 
Create Date: 2026-08-19 11:03:43.132823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fe4c195842d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('icp_config_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'PARTIAL_SUCCESS', 'COMPLETED', 'FAILED', name='runstatus', native_enum=False), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('geography', sa.String(), nullable=True),
    sa.Column('tech_stack', sa.JSON(), nullable=True),
    sa.Column('funding_stage', sa.String(), nullable=True),
    sa.Column('growth_signal', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('RAW', 'ADVANCED', 'REJECTED_EARLY', 'ENRICHED', 'ENRICHMENT_FAILED', 'FIT_EVALUATED', 'REJECTED', 'RESEARCHED', 'QUALIFIED', 'NOT_QUALIFIED', 'REVIEWED', 'SYNCED', name='accountstatus', native_enum=False), nullable=False),
    sa.Column('fit_tier', sa.Enum('TIER_1', 'TIER_2', 'TIER_3', 'REJECTED', 'INSUFFICIENT_DATA', name='fittier', native_enum=False), nullable=True),
    sa.Column('discovered_in_run_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['discovered_in_run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_domain'), 'accounts', ['domain'], unique=True)
    op.create_table('contacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('seniority', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('email_confidence', sa.String(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('DISCOVERED', 'ENRICHED', 'ENRICHMENT_FAILED', name='contactstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fit_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('pass_type', sa.Enum('PREFILTER', 'FULL', name='fitpasstype', native_enum=False), nullable=False),
    sa.Column('tier', sa.Enum('TIER_1', 'TIER_2', 'TIER_3', 'REJECTED', 'INSUFFICIENT_DATA', name='fittier', native_enum=False), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('claim', sa.String(), nullable=False),
    sa.Column('source_type', sa.Enum('PROVIDER_API', 'AI_INFERRED', 'MANUAL', name='evidencesourcetype', native_enum=False), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('confidence', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='confidencelevel', native_enum=False), nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('external_call_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=True),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('operation', sa.String(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILED_RETRYABLE', 'FAILED_NON_RETRYABLE', 'FAILED_EXHAUSTED', name='callstatus', native_enum=False), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provider_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=True),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('operation', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qualification_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('QUALIFIED', 'NOT_QUALIFIED', 'NEEDS_MORE_INFO', name='qualificationstatus', native_enum=False), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_ids', sa.JSON(), nullable=False),
    sa.Column('rationale_text', sa.String(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prospect_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('qualification_result_id', sa.Uuid(), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=True),
    sa.Column('priority_rank', sa.Integer(), nullable=True),
    sa.Column('review_decision', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='reviewdecision', native_enum=False), nullable=False),
    sa.Column('review_reason', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('crm_object_id', sa.String(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['qualification_result_id'], ['qualification_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prospect_records')
    op.drop_table('qualification_results')
    op.drop_table('provider_records')
    op.drop_table('external_call_attempts')
    op.drop_table('evidence')
    op.drop_table('fit_results')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_accounts_domain'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_table('runs')
    # ### end Alembic commands ###
